version: '2'
services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./wordpress:/var/www/
            - ./nginx/logs:/var/log/nginx/
        links:
            - php:php

    php:
        build: ./php
        ports:
            - ":9000"
        container_name: php
        restart: always
        volumes:
            - ./wordpress:/var/www/
        links:
            - mariadb:mariadb

    mariadb:
        container_name: mariadb
        restart: always
        build: ./mariadb
        ports:
            - "3306:3306"
        volumes:
          - ./mariadb/lib/:/var/lib/mysql:rw
          - ./mariadb/log/:/var/log/mysql:rw
